# Generated by Django 5.0.6 on 2024-06-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Roll_no', models.IntegerField()),
                ('Phone_no', models.PositiveBigIntegerField()),
                ('Standard', models.IntegerField()),
                ('Tamil', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
            ],
        ),
    ]
